task_type: FARGATE
network_mode: awsvpc

cpu: 256
memory: 512

step_function_iam_policies:
  run_task:
    action:
      - ecs:RunTask
    resource:
      - Fn::Sub: arn:aws:ecs:::task-definition/${EnvironmentName}-*