task_type: FARGATE
network_mode: awsvpc

cpu: 256
memory: 512

step_function_iam_policies:
  run_task:
    action:
      - ecs:RunTask
    resource:
      - Fn::Sub: arn:aws:ecs:::task-definition/${EnvironmentName}-*


state_machine: |
  {
    "Comment": "",
    "StartAt": "Run Task",
    "TimeoutSeconds": 3600,
    "States": {
      "Run Task": {
        "Type": "Task",
        "Resource": "arn:aws:states:::ecs:runTask.sync",
        "Parameters": {
          "LaunchType": "FARGATE",
          "Cluster": "${EcsCluster}",
          "TaskDefinition": "${Task}",
          "NetworkConfiguration": {
            "AwsvpcConfiguration": {
              "Subnets": "${SubnetId}",
              "AssignPublicIp": "DISABLED"
            }
          }
        },
        "Next": "Success",
        "Catch": [
            {
              "ErrorEquals": [ "States.ALL" ],
              "Next": "Failure"
            }
        ]
      },
      "Success": {
        "Type": "Succeed",
        "End": true
      },
      "Failure": {
        "Type": "Fail",
        "End": true
      }
    }
  }